apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-web
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx-web
    spec:
      containers:
      - image: nginx
        name: nginx-web
        ports:
        - containerPort: 80
        volumeMounts:
          - name: webvol
            mountPath: /usr/share/nginx/html
      volumes:
        - name: webvol
          hostPath:
            path: /var/lib/jenkins/workspace/Auto_Web_Update/webpage/
